version: '3.0'
services:
  morph:
    build: .
    container_name: morph
    volumes:
      - /path/to/data_directory:/data
    ports:
      - "8545:8545"
      - "8551:8551"
      - "26658:26658"
      - "26657:26657"
      - "26656:26656"
      - "26660:26660"
    environment:
      - TZ=UTC
